mapsize: [0, 20, 0, 20]
dt: 0.1

robots:
  - type: "doubleint" 
    x0: [19.5, 10, 0.001, 0.001]
    target: [0.5, 10, 0, 0]
    noise: [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
    radius: 0.5



obstacles:
  - number: 1
    distribution: {name: 'manual'}
    behavior: {mode: 'nominal', factor: 1.5, type: only_obs} #  only_obs all_obj
    kinematics: 'int' # int diff
    x0: [[0, 9.75]] 
    target: [[20, 9.75]]
    noise: [[0.07, 0.07], [0.0, 0.0, 0.0, 0.0]]
    u_max: [1.8,1.8]
    u_min: [-1.8,1.8]
    radius: 2.5
    color: 'k'
